### ISSUE TITLE
Rename .README.md

### ISSUE THREAD

**Issue by kholland950** [kesslern/configs#1]
Remove leading '.' from file name so it appears as a README on github.

**Comment by kesslern** [comment]
Following readme instructions checks out the repo to your home directory. I don't want to pollute my home directory with a README.md file or put the readme in a hidden directory.

**Comment by kholland950** [comment]
You could make a "conf" directory or something to separate the README from the rest of the config to avoid this issue. I would much appreciate integrate github README support

**Comment by kesslern** [comment]
this is why people don't like github
